---
title: "Take Home Exercise 2"
author: "edwin"
execute: 
  eval: true
  echo: true
  freeze: true
---

# Installing and loading R packages

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse,sfdep)
```

# The data

```{r}
drug_data <- read.csv("data/thai_drug_offenses_2017_2022.csv")
```

```{r}
thailand_provinces<- st_read(dsn="data/geospatial",
                         layer = "tha_admbnda_adm1_rtsd_20220121")
```

```{r}
# Drop the ADM1_TH column
thailand_provinces <- thailand_provinces %>%
  select(-ADM1_TH,-ADM1_REF,-ADM1ALT1EN,-ADM1ALT2EN,-ADM1ALT1TH,-ADM1ALT2EN, -ADM1ALT2TH, -ADM0_TH) %>% 
  rename(province_en = ADM1_EN)

# Drop the province_th column
drug_data <- drug_data %>%
  select(-province_th)
```

```{r}
province_grouped <- drug_data %>%
  group_by(fiscal_year, province_en)

# Example: Summarize the total drug offenses for each group
province_summary <- province_grouped %>%
  summarise(total_offenses = sum(no_cases, na.rm = TRUE), .groups = "keep")
```

```{r}
typeOffenses_grouped <- drug_data %>%
  group_by(fiscal_year, types_of_drug_offenses)

typeOffenses_summary <- typeOffenses_grouped %>% 
  summarise(total_offenses = sum(no_cases, na.rm = TRUE), .groups = "keep")
```

```{r}
# Join the drug abuse data with province polygons
combined_data <- thailand_provinces %>%
  left_join(drug_data, by = "province_en")

```

```{r}
# Join the drug abuse province data with province polygons
combined_province_data <- thailand_provinces %>%
  left_join(province_summary, by = "province_en")
```

```{r}
print(st_geometry_type(combined_data))
```

```{r}
# Create a choropleth map using tmap
tm_shape(combined_data) +
  tm_polygons("total_offenses", 
              title = "Number of Cases",
              palette = "Blues", 
              style = "quantile", 
              n = 5) +
  tm_facets(by = "fiscal_year", nrow = 2, free.coords = FALSE) +
  tm_layout(main.title = "Drug Offense Cases in Thailand by Province and Fiscal Year",
            main.title.size = 1.5,
            legend.outside = TRUE)
```

```{r}
# Example: KDE (if you have point data)
tm_shape(combined_data) +
  tm_polygons("total_offenses", 
              title = "Number of Drug Cases", 
              palette = "Oranges", 
              style = "cont") +  # Continuous color scale
  tm_layout(main.title = "KDE Map of Drug Offense Density", 
            legend.outside = TRUE)
```

```{r}
# Create neighbors list
neighbors <- st_contiguity(combined_province_data)
```
