project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: Hands-on Exercises
      menu:
        - text: Hands-on Exercise 1
          href: Hands_On_Ex/Hands_On_Ex1/hands_on_ex1.html
        - text: Hands-on Exercise 2
          href: Hands_On_Ex/Hands_On_Ex2/hands_on_ex2.html
        - text: Hands-on Exercise 3
          href: Hands_On_Ex/Hands_On_Ex3/hands_on_ex3.html
        - text: Hands-on Exercise 3b
          href: Hands_On_Ex/Hands_On_Ex3/hands_on_ex3b.html
          
    - text: In-Class Exercises
      menu:
        - text: In-Class Exercise 1
          href: In_Class_Excercise/In_Class_Ex1/In_Class_Ex1.html
        - text: In-Class Exercise 2
          href: In_Class_Excercise/In_Class_Ex2/In_Class_Ex2.html
        - text: In-Class Exercise 3
          href: In_Class_Excercise/In_Class_Ex3/In_Class_Ex3.html
        - text: In-Class Exercise 4
          href: In_Class_Excercise/In_Class_Ex4/In_Class_Ex4.html
    - text: Take-Home Exercises
      menu:
        - text: Take-Home Exercise 1
          href: In_Class_Excercise/In_Class_Ex1/In_Class_Ex1.html
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

