project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: Hands-on Exercises
      menu:
        - text: Hands-on Exercise 1
          href: Hands_On_Ex/Hands_On_Ex1/hands_on_ex1.html
        - text: Hands-on Exercise 2
          href: Hands_On_Ex/Hands_On_Ex2/hands_on_ex2.html
        - text: Hands-on Exercise 3
          href: Hands_On_Ex/Hands_On_Ex3/hands_on_ex3.html
        - text: Hands-on Exercise 3b
          href: Hands_On_Ex/Hands_On_Ex3/hands_on_ex3b.html
        - text: Hands-on Exercise 4
          href: Hands_On_Ex/Hands_On_Ex4/hands_on_ex4.html
        - text: Hands-on Exercise 5
          href: Hands_On_Ex/Hands_On_Ex5/hands_on_ex5.html
        - text: Hands-on Exercise 6
          href: Hands_On_Ex/Hands_On_Ex6/hands_on_ex6.html
        - text: Hands-on Exercise 6b
          href: Hands_On_Ex/Hands_On_Ex6/hands_on_ex6b.html
        - text: Hands-on Exercise 7
          href: Hands_On_Ex/Hands_On_Ex7/hands_on_ex7.html
        - text: Hands-on Exercise 8
          href: Hands_On_Ex/Hands_On_Ex8/hands_on_ex8.html
        - text: Hands-on Exercise 9
          href: Hands_On_Ex/Hands_On_Ex9/hands_on_ex9.html
          
    - text: In-Class Exercises
      menu:
        - text: In-Class Exercise 1
          href: In_Class_Excercise/In_Class_Ex1/In_Class_Ex1.html
        - text: In-Class Exercise 2
          href: In_Class_Excercise/In_Class_Ex2/In_Class_Ex2.html
        - text: In-Class Exercise 3
          href: In_Class_Excercise/In_Class_Ex3/In_Class_Ex3.html
        - text: In-Class Exercise 4
          href: In_Class_Excercise/In_Class_Ex4/In_Class_Ex4.html
        - text: In-Class Exercise 5
          href: In_Class_Excercise/In_Class_Ex5/In_Class_Ex5.html
        - text: In-Class Exercise 6
          href: In_Class_Excercise/In_Class_Ex6/In_Class_Ex6.html
        - text: In-Class Exercise 9
          href: In_Class_Excercise/In_Class_Ex9/In_Class_Ex9.html  
          
    - text: Take-Home Exercises
      menu:
        - text: Take-Home Exercise 1
          href: Take_Home_Ex/Take_home_ex1/take_home_ex1.html
        - text: Take-Home Exercise 2
          href: Take_Home_Ex/Take_home_ex2/take_home_ex2.html
        - text: Take-Home Exercise 3
          href: Take_Home_Ex/Take_home_ex3/take_home_ex3.html
    - text: Project
      menu:
        - text: Proposal
          href: project/geospatial project.html
       
         
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

