{
  "hash": "af140b2f0f0826feaaa6771a79f2122d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2: Application of Geospatial Analysis Methods to Discover Thailand Drug Abuse at the Province Level\"\nauthor: \"edwin tan\"\nexecute: \n  eval: true\n  echo: true\n  freeze: true\n---\n\n\n# Background\n\n### 1. **Geopolitical Context**\n\n-   Thailand's proximity to the **Golden Triangle** (the region where the borders of Thailand, Laos, and Myanmar meet) is significant as this area is historically known as a major hub for drug production and trafficking, particularly of opium and heroin. More recently, synthetic drugs like methamphetamine have become prevalent.\n\n-   Thailand serves both as a **transit route** for drugs destined for third countries and as a significant **market** for illicit drugs. This geopolitical factor adds complexity to the issue, as it intersects with international drug trafficking networks and the nation's domestic drug use.\n\n### 2. **Transportation Infrastructure**\n\n-   With the continuous development of transportation infrastructure in Thailand, the movement of drugs becomes easier both within the country and across borders. This infrastructure facilitates not only legitimate commerce but also illegal activities, particularly in regions that border drug-producing areas.\n\n-   Analysts should consider transportation routes and **connectivity** between provinces, as these might correlate with higher rates of drug abuse or trafficking activity in certain regions.\n\n### 3. **Prevalence of Drug Use**\n\n-   Globally, drug use is on the rise, and Thailand reflects this trend. With **2.7 million youths** reportedly using drugs, and **300,000** needing drug treatment, it’s clear that drug abuse is a pervasive social problem.\n\n-   A particular focus should be placed on **youth involvement**, especially among **vocational-school students**, as they show a higher incidence of drug abuse compared to secondary-school students. Analysts may want to explore why this demographic is more vulnerable and how their environment (e.g., educational settings, social circles) contributes to the problem.\n\n### 4. **Health, Financial, and Social Impact**\n\n-   Drug abuse has severe **health consequences**, including addiction, overdose, and the spread of infectious diseases (e.g., HIV, hepatitis).\n\n-   The **financial cost** includes both the economic burden on healthcare systems and the loss of productivity, particularly among the youth. Social consequences may include increased crime rates, family breakdowns, and reduced educational and employment opportunities for affected individuals.\n\n-   **Social services** and the **healthcare system** in Thailand are likely under strain, with increasing demands for drug treatment and rehabilitation programs.\n\n### 5. **Geographic Distribution of Drug Use**\n\n-   By analyzing the **geographic distribution** of drug use cases across provinces, one can identify patterns that may suggest localized factors contributing to drug abuse. This may include proximity to trafficking routes, socio-economic disparities, or regional differences in enforcement or education.\n\n-   Analysts should be prepared to look at this distribution in relation to **population density**, economic activity, access to healthcare, and law enforcement effectiveness. Yearly data will also allow for the identification of **trends over time**, such as regions where drug abuse is increasing or decreasing.\n\n### 6. **Policy and Enforcement**\n\n-   Thailand has a strong **anti-drug policy**, including harsh penalties for drug-related offenses. However, the effectiveness of these policies is debatable given the continued rise in drug use. An analyst should consider the impact of these policies, including whether they have driven drug abuse underground or led to unintended consequences, such as higher incarceration rates.\n\nIn analyzing this data, it is crucial to contextualize it within **regional geopolitics**, **infrastructure development**, **social factors**, and **government responses**. Mapping drug abuse cases by year and province can help to uncover hotspots, trends, and areas where intervention may be most needed. Understanding the **root causes** of drug abuse among vulnerable populations, particularly youths, is also essential in crafting effective policy recommendations and targeted interventions.\n\n# Installing and loading R packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse,sfdep)\n```\n:::\n\n\n-   **sf**: This package is used for handling spatial data in R, allowing for operations on simple features (geometric objects).\n\n-   **spdep**: This package provides tools for spatial dependence, including functions for spatial weights and models.\n\n-   **tmap**: A package designed for thematic mapping, making it easy to create static and interactive maps.\n\n-   **tidyverse**: A collection of R packages designed for data science, including `ggplot2`, `dplyr`, and others that simplify data manipulation and visualization.\n\n-   **sfdep**: This package focuses on spatial dependency, providing tools for estimating spatial autocorrelation and conducting related analyses.\n\n# The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_data <- read.csv(\"data/thai_drug_offenses_2017_2022.csv\")\n```\n:::\n\n\nread a CSV (Comma-Separated Values) file containing data on drug offenses in Thailand from the years 2017 to 2022. Here’s a breakdown of its components and purpose:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(drug_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fiscal_year   types_of_drug_offenses    no_cases       province_th       \n Min.   :2017   Length:7392            Min.   :    0.0   Length:7392       \n 1st Qu.:2018   Class :character       1st Qu.:    1.0   Class :character  \n Median :2020   Mode  :character       Median :   70.0   Mode  :character  \n Mean   :2020                          Mean   :  535.3                     \n 3rd Qu.:2021                          3rd Qu.:  623.0                     \n Max.   :2022                          Max.   :17131.0                     \n province_en       \n Length:7392       \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n```\n\n\n:::\n:::\n\n\n-   **Fiscal Year**:\n\n    -   The `fiscal_year` variable ranges from **2017 to 2022**. This indicates that the dataset covers a total of **6 years** of drug offense data.\n\n    -   The median year is **2020**, and the mean year is also **2020**, suggesting that the data is centered around this time period.\n\n-   **Types of Drug Offenses**:\n\n    -   The `types_of_drug_offenses` variable is categorical (character type) and contains a variety of different drug offenses.\n\n    -   The distribution of types may be analyzed further to determine which types of offenses are most common over the years.\n\n-   **Number of Cases (`no_cases`)**:\n\n    -   The `no_cases` variable indicates the number of drug offense cases recorded in the dataset.\n\n    -   **Minimum**: There are instances with **0 cases**, indicating that in some provinces or years, no drug offenses were reported.\n\n    -   **1st Quartile**: The first quartile (25th percentile) shows that **25% of the cases** had **1 or fewer** offenses, indicating low numbers of cases in a substantial portion of the dataset.\n\n    -   **Median**: The median of **70 cases** suggests that half of the entries reported **70 or fewer offenses**, highlighting a significant number of cases in the upper half.\n\n    -   **Mean**: The average number of cases is **535.3**, which is considerably higher than the median, suggesting that there are some provinces or years with exceptionally high numbers of cases that skew the average upwards.\n\n    -   **3rd Quartile**: The third quartile indicates that **75% of the cases** reported **623 or fewer offenses**, reflecting that a smaller portion of the dataset has a much larger number of offenses.\n\n    -   **Maximum**: The maximum number of cases reported is **17,131**, which indicates a significant outlier. This could represent a specific province or year with particularly high drug offenses that may require further investigation.\n\n-   **Province**:\n\n    -   The `province_en` variable, also categorical, lists the provinces in which the drug offenses occurred. The length of this variable being **7392** indicates that there are multiple entries for different provinces and years.\n\n    -   Analysis of this variable could reveal geographic patterns of drug offenses, helping identify regions that are more heavily impacted by drug issues.\n\nOnce the provincial boundaries are loaded into the `thailand_provinces` variable as a Simple Features (sf) object, it can be used for various analyse\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_provinces<- st_read(dsn=\"data/geospatial\",\n                         layer = \"tha_admbnda_adm1_rtsd_20220121\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `tha_admbnda_adm1_rtsd_20220121' from data source \n  `C:\\edwing444\\IS415-GAA\\Take_Home_Ex\\Take_home_ex2\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop the ADM1_TH column\nthailand_provinces <- thailand_provinces %>%\n  select(-ADM1_TH,-ADM1_REF,-ADM1ALT1EN,-ADM1ALT2EN,-ADM1ALT1TH,-ADM1ALT2EN, -ADM1ALT2TH, -ADM0_TH) %>% \n  rename(province_en = ADM1_EN)\n\n# Drop the province_th column\ndrug_data <- drug_data %>%\n  select(-province_th)\n```\n:::\n\n\nI simplify the `thailand_provinces` dataset by removing columns that are not needed for further analysis, thus making the dataset cleaner and more manageable. Also, i rename the `ADM1_EN` column to `province_en`, which contains the province names in English. This provides a clearer and more intuitive column name for future analysis.\\\n\\\nNext, I remove the `province_th` column from the `drug_data` dataset, likely because it contains redundant or unnecessary information, especially if the `thailand_provinces` dataset now includes the relevant province information in English. Dropping this column helps streamline the `drug_data` dataset, focusing on the necessary columns that are crucial for the analysis of drug offenses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_grouped <- drug_data %>%\n  group_by(fiscal_year, province_en)\n\n# Example: Summarize the total drug offenses for each group\nprovince_summary <- province_grouped %>%\n  summarise(total_offenses = sum(no_cases, na.rm = TRUE), .groups = \"keep\")\n```\n:::\n\n\nThis grouping allows for subsequent calculations to be performed within these groups, making it easier to analyze trends and patterns of drug offenses over time and across different provinces.\n\nThe result after summarising is a new data frame `province_summary` that contains three columns: `fiscal_year`, `province_en`, and `total_offenses`, which reflects the total number of offenses recorded for each province in each fiscal year.\n\nThe argument `.groups = \"keep\"` retains the grouping structure of the original data frame in the summarized output, which may be useful for further analysis or visualizations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join the drug abuse data with province polygons\ncombined_data <- thailand_provinces %>%\n  left_join(drug_data, by = \"province_en\")\n```\n:::\n\n\nNow I will merge the two datasets in a way that retains all the rows from the `thailand_provinces` dataset and includes matching rows from the `drug_data` dataset based on the `province_en` column.\n\n-   If a province in `thailand_provinces` does not have corresponding data in `drug_data`, the resulting `combined_data` will still include that province, but the columns from `drug_data` will contain `NA` (missing values).\n\nThe purpose of this operation is to create a combined dataset that integrates geographic information about the provinces with the corresponding drug offense data. This integration is used for mapping the data to **understand how the data looks like**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join the drug abuse province data with province polygons\ncombined_province_data <- thailand_provinces %>%\n  left_join(province_summary)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(province_en)`\n```\n\n\n:::\n:::\n\n\nThe above merges the geographic data of provinces with the summarized drug offense data to create a comprehensive dataset that includes both spatial and analytical information.\n\n-   The join is done based on the common columns present in both datasets. Since `province_summary` is assumed to have the `province_en` column, it will merge the summarized drug offense totals for each province.\n\n-   If there are provinces in `thailand_provinces` that do not have corresponding entries in `province_summary`, they will still be included in the resulting dataset (`combined_province_data`), but the columns from `province_summary` will contain `NA` (missing values).\n\nThis integration is essential for **spatial analysis and for visualizing the data on maps**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_province_data <- combined_province_data %>%\n  filter(!is.na(total_offenses))\n```\n:::\n\n\nNow I clean the dataset by excluding any entries that do not have a valid total number of drug offenses.\n\nRemoving rows with `NA` values in the `total_offenses` column ensures that subsequent analyses or visualizations are based on complete data, leading to more accurate and reliable results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(st_geometry_type(combined_province_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n  [6] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [11] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [16] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [21] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [26] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [31] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [36] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [41] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [46] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [51] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [56] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [61] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [66] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [71] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [76] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [81] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [86] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [91] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [96] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[101] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[106] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[111] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[116] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[121] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[126] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[131] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[136] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[141] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[146] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[151] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[156] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[161] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[166] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[171] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[176] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[181] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[186] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[191] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[196] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[201] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[206] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[211] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[216] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[221] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[226] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[231] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[236] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[241] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[246] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[251] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[256] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[261] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[266] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[271] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[276] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[281] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[286] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[291] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[296] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[301] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[306] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[311] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[316] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[321] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[326] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[331] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[336] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[341] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[346] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[351] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[356] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[361] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[366] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[371] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[376] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[381] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[386] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[391] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[396] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[401] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[406] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[411] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[416] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[421] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[426] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[431] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[436] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[441] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[446] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\nIt is \"MULTIPOLYGON\", it signifies that some provinces may consist of multiple, non-contiguous areas.\n\n# Understanding the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a choropleth map using tmap\ntm_shape(combined_province_data) +\n  tm_polygons(\"total_offenses\", \n              title = \"Number of Cases\",\n              palette = \"Blues\", \n              style = \"quantile\", \n              n = 5) +\n  tm_facets(by = \"fiscal_year\", nrow = 2, free.coords = FALSE) +\n  tm_layout(main.title = \"Drug Offense Cases in Thailand by Province and Fiscal Year\",\n            main.title.size = 1.5,\n            legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### **1. Spatial Distribution Analysis**\n\n-   **Northern Thailand:**\n\n    -   The consistently high rates of drug offenses in the northern provinces, particularly Chiang Mai, Chiang Rai, and Mae Hong Son, align with the geographical proximity to the *Golden Triangle*, a region where Myanmar, Laos, and Thailand meet and which has historically been a hub for drug production and trafficking, particularly opium and methamphetamines.\n\n    -   These provinces are on critical drug trafficking routes. Both production and cross-border smuggling of drugs likely lead to higher drug-related arrests and offenses in this area.\n\n-   **Southern Thailand:**\n\n    -   The fluctuation between high and low rates of drug offenses in southern provinces like Yala, Pattani, and Narathiwat could be influenced by political instability and insurgency. The region’s volatile security situation might make it easier for criminal networks to operate in some years, while in others, heavy military or police operations may reduce drug-related activity.\n\n    -   The coastal access of southern provinces also suggests the possibility of drug smuggling by sea. Major coastal routes may play a role in the drug trade, with some provinces acting as transit points.\n\n-   **Central Thailand:**\n\n    -   Central Thailand, including the Bangkok metropolitan area, generally shows lower rates of drug offenses compared to the north and south. However, the fluctuation of rates in this area can be attributed to its urban density, economic activity, and the focus on trafficking and distribution rather than production. Law enforcement in urban centers tends to be more rigorous, which may help in keeping offense rates relatively low.\n\n#### **2. Temporal Trends**\n\n-   **2017-2019:**\n\n    -   During this period, most provinces in Thailand experienced a rise in drug offense cases. This may be due to increased trafficking activities or a rise in drug production in neighboring countries.\n\n    -   Another potential factor could be Thailand's more stringent anti-drug measures introduced in these years. If law enforcement efforts intensified, we might expect an initial spike in offenses as more arrests were made.\n\n-   **2020:**\n\n    -   The slight decrease in offenses in some provinces could be linked to COVID-19 lockdown measures, which likely disrupted trafficking routes and limited the mobility of both traffickers and users.\n\n    -   Border closures, particularly with Myanmar and Laos, could have contributed to this decline, as these regions are significant sources of illicit drugs.\n\n-   **2021-2022:**\n\n    -   With data missing for 2022, it's difficult to analyze this year fully. However, the continuation of trends into 2021 suggests a rebound in drug offenses, possibly as COVID-19 restrictions eased. This could indicate a resumption of trafficking activities.\n\n#### **3. Hotspot Analysis**\n\n-   **Northern Provinces:**\n\n    -   Provinces like Chiang Mai, Chiang Rai, and Mae Hong Son are recurrent hotspots for drug offenses, again underscoring their strategic importance in trafficking routes from the *Golden Triangle*. The mountainous terrain and porous borders make monitoring and controlling these regions challenging, allowing for consistent trafficking operations.\n\n-   **Southern Provinces:**\n\n    -   Yala, Pattani, and Narathiwat show elevated rates, especially in certain years. The presence of insurgent groups in these regions may contribute to higher rates of drug offenses, as some of these groups could be involved in the drug trade to fund their activities. Moreover, the difficult security situation in the south complicates law enforcement efforts.\n\n#### **4. Potential Explanations**\n\n-   **Geographical Factors:**\n\n    -   Proximity to drug production areas in Myanmar and Laos is one of the key drivers behind high drug offense rates in northern Thailand. Major highways, rivers, and mountain passes in these areas serve as conduits for the drug trade, with drugs entering Thailand via these borders.\n\n-   **Socioeconomic Conditions:**\n\n    -   Regions with high poverty and unemployment often experience higher rates of drug-related crimes. Individuals in these regions may become involved in drug trafficking as a means of survival, particularly in provinces where economic opportunities are limited. Socioeconomic data for these provinces could provide additional insights into the correlation between poverty and drug offenses.\n\n-   **Governance and Law Enforcement:**\n\n    -   Variations in law enforcement efforts across regions can significantly affect the number of recorded drug offenses. Regions with strong, well-resourced law enforcement may see higher numbers of arrests, as officers are more capable of apprehending offenders. Conversely, provinces with less effective governance or law enforcement may underreport drug activity.\n\n-   **Drug Production and Trafficking Routes:**\n\n    -   Further analysis could focus on the types of drugs that are most prevalent in these regions. Methamphetamine (often trafficked from Myanmar) is the most commonly seized drug in Thailand. Understanding where these drugs are produced, the routes they take to reach distribution points, and the socio-political factors that enable trafficking could refine this analysis.\n\n#### **5. Further Analysis and Next Steps**\n\n-   **Spatial Autocorrelation:**\n\n    -   Conducting a global spatial autocorrelation analysis using Moran’s I could help determine whether drug offenses are spatially clustered or dispersed across Thailand. A local analysis (such as Getis-Ord Gi\\*) could then identify specific provinces that function as statistically significant hotspots.\n\n-   **Socioeconomic Data Integration:**\n\n    -   Integrating socioeconomic indicators like income levels, education rates, and unemployment with drug offense data would provide a more comprehensive understanding of the drivers behind the spatial patterns observed. This can be done using methods such as geographically weighted regression (GWR).\n\n-   **Temporal Analysis:**\n\n    -   Conducting a spatio-temporal analysis using techniques like kernel density estimation (KDE) for hot-spot detection over time could reveal changes in offense patterns and how these have evolved in response to events such as policy changes or socio-economic developments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example: KDE (if you have point data)\ntm_shape(combined_province_data) +\n  tm_polygons(\"total_offenses\", \n              title = \"Number of Drug Cases\", \n              palette = \"Oranges\", \n              style = \"cont\") +  # Continuous color scale\n  tm_layout(main.title = \"KDE Map of Drug Offense Density\", \n            legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n#### **1. Spatial Clustering**\n\n-   **Northern Thailand:**\n\n    -   The clustering in northern Thailand, particularly around Chiang Mai, Chiang Rai, and Mae Hong Son, is likely driven by its geographical location. This area is part of the *Golden Triangle*, which has historically been a center for opium production and now methamphetamine trafficking. The mountainous terrain and porous borders with Myanmar and Laos make this region an attractive route for traffickers, contributing to consistently high offense rates.\n\n    -   The clustering observed could also be due to the enhanced focus of law enforcement in these regions. Hotspots may emerge not only because of trafficking but due to targeted anti-drug operations by authorities in this area.\n\n-   **Southern Thailand:**\n\n    -   The southern provinces of Yala, Pattani, and Narathiwat also exhibit significant spatial clustering of drug offenses. These provinces are known for political instability and ongoing insurgency, which can create a permissive environment for criminal activities, including drug trafficking.\n\n    -   Additionally, the proximity to maritime routes and porous borders with Malaysia may facilitate smuggling operations, adding to the concentration of drug offenses in this region.\n\n-   **Central Thailand:**\n\n    -   Central Thailand generally shows lower densities of drug offenses, with scattered clusters in some urban areas. This may be because central provinces, including the capital city Bangkok, serve more as distribution hubs rather than centers of drug production or trafficking. Law enforcement is also generally stronger in central Thailand, which could help suppress visible clustering of offenses.\n\n#### **2. Density Gradients**\n\n-   The density gradient maps of drug offenses show a clear geographic divide, with the north and south experiencing much higher densities than the central region. These gradients are visual representations of where drug offenses are most concentrated.\n\n    -   **Darker shades in northern and southern Thailand** indicate high densities of offenses, reflecting the concentration of trafficking routes and the presence of vulnerable populations in these regions.\n\n    -   **Lighter shades in central Thailand** suggest a lower concentration of offenses, potentially due to more effective governance, urban infrastructure, and better socioeconomic conditions.\n\n#### **3. Potential Explanations**\n\n-   **Geographical Factors:**\n\n    -   Northern Thailand’s proximity to the borders of Myanmar and Laos is a critical factor in its role in drug trafficking. Drugs, particularly methamphetamines, are produced in these neighboring countries and trafficked through northern Thailand to other parts of the country and beyond. The challenging terrain and remote border areas make it easier for traffickers to move goods undetected, leading to clusters of drug-related offenses.\n\n    -   In the south, proximity to maritime smuggling routes and the border with Malaysia plays a significant role in the concentration of drug offenses. Maritime routes offer traffickers an alternative to land routes, making it a key transit point for drugs coming from Southeast Asia.\n\n-   **Socioeconomic Conditions:**\n\n    -   High poverty and unemployment in regions like northern and southern Thailand can fuel drug-related activities. People in economically deprived areas may become involved in trafficking and drug-related crimes due to a lack of alternatives for economic survival.\n\n    -   In contrast, the relatively wealthier and more developed central region may see fewer clusters of drug offenses due to better employment opportunities, higher educational attainment, and stronger institutions.\n\n-   **Governance and Law Enforcement:**\n\n    -   The clustering of drug offenses in northern and southern Thailand could be influenced by variations in the effectiveness of law enforcement. In regions where law enforcement is weaker or less present, trafficking routes may flourish, resulting in higher densities of drug offenses.\n\n    -   Conversely, central Thailand may benefit from stronger governance and more rigorous anti-drug initiatives, leading to lower densities of drug offenses. The presence of more robust legal frameworks and security forces in urban areas like Bangkok also contributes to the scattered nature of drug-related offenses in this region.\n\n-   **Drug Production and Trafficking Routes:**\n\n    -   The specific types of drugs and their production and trafficking routes are crucial to understanding these spatial patterns. In northern Thailand, methamphetamine is the primary drug being trafficked from neighboring Myanmar. In southern Thailand, the influence of transnational drug networks and the role of maritime smuggling routes add complexity to the spatial patterns observed. Further analysis of drug types and their transit paths would reveal more about how different trafficking networks operate across the country.\n\n#### **4. Further Analysis**\n\n-   **Spatial Autocorrelation Analysis:**\n\n    -   Performing a spatial autocorrelation test like Moran’s I can statistically confirm the clustering patterns observed in the north and south. A local indicator of spatial association (LISA) could also help to pinpoint specific provinces contributing most to these clusters.\n\n# Preparing data for **Global Measures of Spatial Autocorrelation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|eval: false\n# Create neighbors list\nneighbors <- st_contiguity(combined_province_data)\n```\n:::\n\n\nI create a **contiguity-based neighbors list** for spatial analysis\n\n`st_contiguity()` is part of the **sfdep** package, which is designed for working with spatial dependencies.\n\n-   **Contiguity** refers to spatial units (in this case, provinces) that share common boundaries. When two provinces share a border, they are considered \"neighbors.\"\n\n-   The function creates a list of neighboring provinces based on their shared borders.\n\nThe result is a list where each province has an associated set of neighboring provinces.\\\n\n### Save Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(neighbors,\"data/rds/neighbors.rds\")\n```\n:::\n\n\n### Read Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneighbors<-read_rds(\"data/rds/neighbors.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(combined_province_data$total_offenses)  # Check the length of your data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 450\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(neighbors)  # Check the number of units in the spatial weights matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 450\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlistw <- nb2listw(neighbors)\n```\n:::\n\n\nNow we convert a **neighbors list** (such as the one I created earlier with `st_contiguity()`) into a **spatial weights matrix** (stored as `listw`). This is an important step in spatial analysis because it allows me to quantify the relationships between geographic units (in this case, provinces) in terms of spatial dependence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert neighbors list to weights list\nweights_list <- nb2listw(neighbors, style = \"W\")\n```\n:::\n\n\nThis command converts the **neighbors list** into a **spatial weights matrix** (stored as `weights_list`), where the weights are row-standardized. The weights matrix is used for spatial analysis tasks like calculating spatial autocorrelation or running spatial regression models.\n\n# Calculating Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Moran's I\nmoran_result <- moran.test(combined_province_data$total_offenses, listw)\nprint(moran_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  combined_province_data$total_offenses  \nweights: listw    \n\nMoran I statistic standard deviate = 16.077, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     0.1903562142     -0.0022271715      0.0001434901 \n```\n\n\n:::\n:::\n\n\n**Moran's I** is a measure of spatial autocorrelation, which indicates whether values of a variable at nearby locations are more similar or more different than expected by chance. It ranges from -1 to 1\n\n**Moran's I Statistic: 0.1903562142**\n\n-   This value suggests a **weak positive spatial autocorrelation**. In simple terms, it indicates that provinces with higher drug offense rates are **slightly more likely to be near other provinces** with similarly high offense rates, compared to a random distribution. The positive value means that nearby provinces tend to have **similar offense levels**, but since it's close to 0, the spatial relationship is not particularly strong.\n\n-   **Weak autocorrelation** can indicate that, while there is some degree of clustering, the spatial distribution of offenses isn't driven solely by geographic proximity. Other factors, such as socioeconomic conditions, local law enforcement efforts, and specific drug trafficking routes, may play a larger role in shaping these patterns.\n\n**Standard Deviate: 16.077**\n\n-   The standard deviate provides a sense of how far the observed Moran's I statistic is from the expected value under the assumption of random spatial patterns. A standard deviate of **16.077** is quite high, indicating that the observed value is **far from random** and suggests a significant deviation from the null hypothesis of no spatial autocorrelation.\n\n-   This means that even though the spatial autocorrelation is weak, the structure observed is still **statistically significant**.\n\n**p-value: \\< 2.2e-16**\n\n-   This **extremely small p-value** (\\< 2.2e-16) indicates that the observed Moran's I statistic is **highly unlikely to have occurred by chance**. It provides strong evidence that **spatial clustering is present** in the dataset. Therefore, we can confidently reject the null hypothesis (which assumes no spatial autocorrelation) and conclude that there is some degree of spatial clustering among provinces with higher rates of drug offenses.\n\n**Expectation and Variance**\n\n-   The expectation and variance provide the benchmark for understanding whether the observed Moran's I statistic deviates significantly from random chance. In this case, the strong statistical significance (p-value) indicates that the observed Moran's I value is meaningfully different from what we would expect if there were no spatial autocorrelation.\n\n### Conclusion and Implications\n\n-   **Weak but Significant Spatial Clustering**: Although the Moran’s I statistic indicates only weak positive autocorrelation, the small p-value confirms that the spatial clustering observed is not random. Provinces with high drug offenses tend to **cluster geographically**, but the strength of the clustering effect is not particularly strong.\n\n-   **Geographically Linked Factors**: The weak positive autocorrelation suggests that geographical proximity does play a role, but it's not the only factor influencing the distribution of offenses. Other variables—such as **drug trafficking routes, socio-economic conditions**, and **local governance**—likely contribute to the patterns seen across provinces.\n\n-   **Further Spatial Analysis Needed**: To better understand this weak spatial autocorrelation, additional spatial techniques could be employed:\n\n    -   **Local Indicators of Spatial Association (LISA)**: LISA can help identify local clusters of high or low values and highlight provinces that deviate from the overall trend.\n\n**Conclusion:**\n\nThis analysis provides a foundational understanding of the spatial distribution of drug offenses in Thailand and suggests that while proximity plays a role, other non-spatial factors may also significantly contribute to the clustering patterns.\n\n# Global measures of Spatial Association\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|eval: false\nwm_thai_g <- combined_province_data %>% \n  mutate(nb=st_contiguity(geometry),\n         wt=st_weights(nb,\n                       style=\"W\"),\n         .before = 1)\n```\n:::\n\n\n### Save Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(wm_thai_g,\"data/rds/wm_thai_g.rds\")\n```\n:::\n\n\n### Read Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_thai_g<-read_rds(\"data/rds/wm_thai_g.rds\")\n```\n:::\n\n\n## Computing Global Moran'I\n\nglobal_moran() function is used to compute Moran's I value. Different from sdep package, the output is a tibble data.frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_thai_g$total_offenses,\n                       wm_thai_g$nb,\n                       wm_thai_g$wt)\nglimpse(moranI)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 2\n $ I: num 0.19\n $ K: num 21.8\n```\n\n\n:::\n:::\n\n\n### Interpretation of Moran's I Results:\n\n1.  **Moran's I Statistic (\\$I\\$): 0.19**\n\n    -   This value represents the global Moran's I statistic for the dataset, which is **0.19**. It suggests a **weak positive spatial autocorrelation**. In other words, provinces with **higher drug offense rates** tend to be **slightly more clustered together geographically** than what would be expected under a random distribution.\n\n    -   Although the autocorrelation is positive, it's relatively weak, implying that while some clustering is present, it is not a strong spatial dependency.\n\n2.  **Z-Score (\\$K\\$): 21.8**\n\n    -   The **Z-score** of **21.8** provides a standardized measure of how far the observed Moran's I value is from what would be expected under a null hypothesis of no spatial autocorrelation.\n\n    -   A Z-score of 21.8 is **extremely high**, indicating that the observed spatial autocorrelation is **highly statistically significant** and is not likely to have occurred by random chance. This strongly supports the existence of spatial clustering in the data.\n\n### Conclusion:\n\nThe analysis reveals a **statistically significant but weak positive spatial autocorrelation** in the distribution of drug offenses across the provinces. While the clustering is not particularly strong, it is **unlikely to be random** and suggests that there are **underlying spatial processes** at work. These processes could include factors such as **geographical proximity to drug trafficking routes, socioeconomic conditions**, or **differences in law enforcement practices** across regions. Further analysis could focus on identifying these factors more clearly through **local spatial analysis** and **geographically weighted regression**.\n\n## Performing Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test(wm_thai_g$total_offenses,\n                       wm_thai_g$nb,\n                       wm_thai_g$wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 16.077, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     0.1903562142     -0.0022271715      0.0001434901 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(wm_thai_g$total_offenses,\n                       wm_thai_g$nb,\n                       wm_thai_g$wt,\n                  nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.19036, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n**Output Interpretation:**\n\n1.  **P-value: \\< 2.2e-16**\n\n    -   This **extremely small p-value** indicates that the observed spatial autocorrelation is **highly statistically significant**. Given that the p-value is far below common thresholds (e.g., 0.05 or 0.01), we can confidently **reject the null hypothesis** of no spatial autocorrelation. This means that the observed spatial distribution of drug offenses is not random.\n\n2.  **Interpretation of the Hypothesis Test:**\n\n    -   The **alternative hypothesis** here is that there is **positive spatial autocorrelation** in the data. Since the **Moran's I** value is positive (0.19) and the p-value is extremely low, there is strong evidence to support the conclusion that **provinces with similar levels of drug offenses tend to be located near each other**.\n\n    -   In other words, areas with high offense rates are more likely to be near other areas with high offense rates, and the same applies to areas with lower rates.\n\n3.  **Moran's I Statistic: 0.1903562142**\n\n    -   The **Global Moran's I** of **0.19** suggests a **weak positive spatial autocorrelation**. This implies that there is some clustering of provinces with similar drug offense levels, but the strength of this clustering is not particularly strong.\n\n    -   Despite the weak strength, the spatial pattern is **statistically significant**, meaning that it is unlikely to occur by chance.\n\n4.  **Standard Deviate: 16.077**\n\n    -   This represents the **standard deviation** of the Moran’s I statistic under random permutations (randomly shuffling the data). A value of 16.077 is quite high, indicating that the observed Moran's I is **far from random** and further supports the finding of significant spatial autocorrelation.\n\n5.  **Sample Estimates:**\n\n    -   **Expectation (-0.0022271715):** This is the expected value of the Moran's I statistic if there were no spatial autocorrelation. It is close to zero, as would be expected under the null hypothesis.\n\n    -   **Variance (0.0001434901):** This is the variance of Moran’s I under random permutations. A small variance suggests a **precise estimate** of Moran's I, further supporting the reliability of the result.\n\n### Conclusion:\n\nThe analysis of drug offenses in Thailand using Moran’s I reveals that **drug offenses are spatially clustered**. Provinces with similar drug offense rates tend to be geographically close to each other, even though the strength of the clustering is weak. The results are statistically significant, indicating that this spatial clustering is unlikely to be due to random chance.\n\nThis finding suggests that there may be **underlying spatial processes** influencing the distribution of drug offenses, such as proximity to **drug trafficking routes**, local **socioeconomic conditions**, or **regional law enforcement efforts**. Further analysis, such as **local Moran’s I** or **spatial regression**, could provide more insight into specific areas with higher clustering and the factors driving this spatial pattern.\n\n# Local Moran's I (LISA) calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Local Moran's I (LISA) calculation\nlocal_moran <- localmoran(combined_province_data$total_offenses, listw)\nhead(local_moran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Ii          E.Ii      Var.Ii     Z.Ii Pr(z != E(Ii))\n1 3.915244 -0.0980888574 0.884289023 4.267839   1.973754e-05\n2 4.433758 -0.1405926984 1.207737668 4.162394   3.149282e-05\n3 4.036029 -0.1067510040 0.953136961 4.243403   2.201559e-05\n4 2.934944 -0.0468413687 0.446278092 4.463480   8.063904e-06\n5 2.449271 -0.0305306590 0.295856466 4.559071   5.138033e-06\n6 0.363538 -0.0005377416 0.005372184 4.967253   6.790805e-07\n```\n\n\n:::\n:::\n\n\n**Interpretation of Results:**\n\n-   **Ii values:** Positive values indicate clustering of similar values (hotspots or coldspots), while negative values indicate dispersion of dissimilar values.\n\n-   **Z.Ii and Pr(z != E(Ii))**: High Z-scores and low p-values suggest statistically significant clustering or dispersion.\n\n## Visualisng Local Moran's I (LISA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Local Moran's I (LISA) calculation\nlisa <- localmoran(combined_province_data$total_offenses, listw = weights_list)\ncombined_province_data$lisa <- lisa[, \"Ii\"] \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set tmap mode to interactive or static\ntmap_mode(\"plot\")  # Use \"view\" for interactive\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ntmap mode set to plotting\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a thematic map to visualize Local Moran's I\ntm_shape(combined_province_data) +\n  tm_polygons(\"lisa\", palette = \"viridis\", title = \"Local Moran's I (LISA)\") +\n  tm_layout(title = \"Local Moran's I (LISA) for Drug Abuse in Thailand Provinces\")\n```\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n### Key Observations:\n\n#### 1. **Spatial Clustering:**\n\n-   **Northern Thailand:** Several **hotspots** (areas with higher-than-average drug abuse rates) and **coldspots** (areas with lower-than-average drug abuse rates) are observed. These clusters suggest **significant spatial autocorrelation**, where provinces with high or low drug abuse rates are located near provinces with similar values.\n\n-   **Southern Thailand:** Similar patterns of clustering emerge, with both **hotspots** and **coldspots** present. The distribution indicates the presence of regions with high drug abuse rates concentrated near other regions with similar characteristics.\n\n-   **Central Thailand:** The distribution appears more **scattered**. Clusters are less pronounced, indicating fewer areas where drug abuse rates are spatially concentrated.\n\n#### 2. **Hotspots and Coldspots:**\n\n-   **Hotspots:** These regions, indicated by darker shades, represent areas with **higher drug abuse rates**. These areas exhibit a tendency to cluster geographically with other provinces experiencing similarly high rates. Hotspots are often located near **drug trafficking routes** or regions with **economic and social vulnerabilities**.\n\n-   **Coldspots:** These areas, indicated by lighter shades, represent **lower drug abuse rates**. Coldspots tend to cluster with other provinces with similarly low rates, which may reflect **better law enforcement**, **socioeconomic stability**, or **geographical isolation** from major trafficking routes.\n\n### Potential Explanations and Further Analysis:\n\n#### 1. **Geographical Factors:**\n\n-   Northern Thailand's proximity to **Myanmar and Laos**, both major drug production areas (particularly for methamphetamines), could be influencing the high rates of drug abuse. **Cross-border trafficking** likely contributes to the clustering of hotspots, as these areas may serve as key transit or distribution points.\n\n-   Southern Thailand’s proximity to maritime routes may also influence trafficking patterns, contributing to its observed clustering of drug abuse cases.\n\n#### 2. **Socioeconomic Conditions:**\n\n-   Areas with **high poverty**, **unemployment**, and **limited access to education** are more vulnerable to higher rates of drug abuse. These socioeconomic challenges can create environments where drug trade and use flourish, reinforcing spatial clustering in regions with economic difficulties.\n\n#### 3. **Governance and Law Enforcement:**\n\n-   The effectiveness of local **law enforcement** and **anti-drug initiatives** likely varies across regions. In provinces with stronger law enforcement presence or targeted anti-drug campaigns, drug abuse rates may be lower, leading to the formation of coldspots. Conversely, areas with weaker enforcement may see rising drug abuse, contributing to hotspots.\n\n#### 4. **Drug Production and Trafficking:**\n\n-   **Drug trafficking routes** and **local production** play a significant role in shaping spatial patterns. Regions that lie along key drug trafficking corridors may exhibit clustering of drug abuse, as these areas serve as hubs for drug distribution and consumption. Understanding the types of drugs involved and the logistical routes used for trafficking could provide more context for the clustering observed in Northern and Southern Thailand.\n\n### Conclusion:\n\nThe spatial clustering of drug abuse cases in Thailand reflects complex **geopolitical, socioeconomic, and law enforcement dynamics**. Northern and Southern Thailand, in particular, exhibit significant clustering due to their proximity to trafficking routes, while Central Thailand shows a more dispersed pattern.\n\n# Computing Local Moran's I\n\nLearn how to compute Local Moran's I of GDPPC at county level by using local_moran() of sfdep package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- wm_thai_g %>% \n  mutate(local_moran = local_moran(\n    total_offenses,nb,wt,nsim=99),\n    .before=1) %>% \n  unnest(local_moran)\n```\n:::\n\n\n## Visualising local Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ntmap mode set to plotting\n```\n\n\n:::\n\n```{.r .cell-code}\nmap1 <- tm_shape(lisa)+\n  tm_fill('ii')+\n  tm_borders(alpha=0.5)+\n  tm_view(set.zoom.limits = c(5,8))+\n  tm_layout(\n    main.title = \"local Moran's I of G\",\n    main.title.size = 2\n  )\n\nmap2 <- tm_shape(lisa)+\n  tm_fill('p_ii',\n          breaks = c(0,0.001,0.01,0.05,1),\n          labels = c(\"0.001\",\"0.01\",\"0.05\",\"Not Sig\"))+\n  tm_borders(alpha=0.5)+\n  tm_layout(\n    main.title = \"p=value of local Moran's I \",\n    main.title.size = 0.8\n  )\ntmap_arrange(map1,map2,ncol=2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nVariable(s) \"ii\" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n### Key Observations:\n\n#### **Map 1: Local Moran's I (Ii)**\n\n-   **Spatial Clustering:**\n\n    -   The map reveals distinct areas of spatial clustering, where values of Local Moran's I indicate regions with either high or low drug abuse rates that tend to cluster together. This suggests **significant spatial autocorrelation** in drug abuse patterns across the provinces.\n\n-   **Hotspots (High-High Clusters):**\n\n    -   Provinces shaded darker (values 4 to 5) are indicative of **high drug abuse rates** clustering with other provinces experiencing similarly high rates. These areas may represent key locations for **drug trafficking routes**, high consumption, or poor enforcement.\n\n-   **Coldspots (Low-Low Clusters):**\n\n    -   Lighter shaded provinces (values 1 to 0) signify **low drug abuse rates** clustering with other regions of low rates. These provinces could reflect areas with **effective law enforcement**, **strong social infrastructure**, or **limited access** to drugs.\n\n#### **Map 2: p-value of Local Moran's I (p_ii)**\n\n-   **Statistical Significance:**\n\n    -   The second map showcases provinces where the Local Moran's I is **statistically significant**, meaning the spatial clustering observed is unlikely due to random chance. P-values below **0.05** (shaded regions) mark areas where we have confidence in the clustering observed in **Map 1**.\n\n-   **Significant Clusters:**\n\n    -   Provinces with p-values below 0.05 (and even lower thresholds of 0.01 and 0.001) are areas with statistically significant spatial clustering. These regions can be considered **true hotspots or coldspots**, where drug abuse rates are influenced by strong spatial relationships and not random occurrences.\n\n### **Combined Analysis:**\n\nBy examining **both maps**, we gain deeper insights into spatial patterns of drug abuse:\n\n-   **Identifying Strong Hotspots/Coldspots:**\n\n    -   Provinces that show both **high Local Moran's I values** (darker shades in Map 1) and **low p-values** (significance in Map 2) represent **strong hotspots** of drug abuse. These provinces are not only clustering geographically with high rates but are also statistically significant, meaning this clustering is robust.\n\n    -   Similarly, **coldspots** identified in both maps represent regions where **low drug abuse rates** are geographically clustered with statistical significance.\n\n-   **Policy Implications:**\n\n    -   **Hotspot provinces** may require **enhanced law enforcement**, **social interventions**, and **anti-drug campaigns**, as they are areas with high and concentrated drug abuse.\n\n    -   **Coldspot provinces** may serve as **models** for effective governance, law enforcement, or social strategies that could be replicated in higher-risk areas.\n\n### Conclusion:\n\nThe combined use of Local Moran's I and its corresponding p-values provides a powerful tool to understand the spatial dynamics of drug abuse in Thailand. Provinces with both high Local Moran's I and statistically significant p-values represent **critical areas** for focused interventions, whether they be law enforcement or socioeconomic support measures. This dual analysis helps to prioritize regions where drug abuse is not only high but spatially concentrated and significant.\n\n# Visualisng LISA map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa %>% \n  filter(p_ii < 0.05)\n\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ntmap mode set to plotting\n```\n\n\n:::\n\n```{.r .cell-code}\ntm_shape(lisa)+\n  tm_polygons()+\n  tm_borders(alpha=0.5)+\n  tm_shape(lisa_sig)+\n  tm_fill(\"mean\")+\n  tm_borders(alpha=0.4)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: One tm layer group has duplicated layer types, which are omitted. To\ndraw multiple layers of the same type, use multiple layer groups (i.e. specify\ntm_shape prior to each of them).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n### Key Observations:\n\n#### **Spatial Clustering:**\n\n-   The map demonstrates **significant spatial clustering** in the distribution of drug abuse rates across provinces. This clustering is identified using **Local Moran's I**, a measure that highlights how similar values (high or low rates) are distributed geographically.\n\n#### **High-High Clusters:**\n\n-   **Northern and Southern regions** of Thailand show notable **high-high clusters**, where provinces with **high drug abuse rates** are surrounded by other high-rate provinces. This indicates that drug abuse is not only prevalent in these regions but also **spatially concentrated**, possibly due to factors such as proximity to drug trafficking routes, limited law enforcement, or socioeconomic challenges.\n\n#### **Low-Low Clusters:**\n\n-   Certain provinces in **central and southern Thailand** exhibit **low-low clusters**, meaning that provinces with **low drug abuse rates** tend to be adjacent to other provinces with similarly low rates. These areas may benefit from more **effective governance, law enforcement**, or **better socioeconomic conditions** that help suppress drug-related activities.\n\n#### **Mixed Clusters (Low-High, High-Low):**\n\n-   **Mixed clusters**, where provinces with **low drug abuse rates** are adjacent to provinces with **high rates** (low-high) and vice versa (high-low), indicate **complex spatial relationships**. These areas may be experiencing **border effects** where the spillover of drug abuse from neighboring high-rate provinces contrasts with local conditions, or they may reflect **transitional zones** influenced by different local policies, economic conditions, or enforcement strength.\n\n### **Implications:**\n\nThe spatial patterns observed through **Local Moran's I** provide important insights into the **geographical spread of drug abuse** in Thailand.\n\n-   **High-High clusters** represent critical areas for **targeted intervention** such as increased law enforcement, border control, or community-based prevention programs.\n\n-   **Low-Low clusters** could serve as examples of **effective policy and enforcement** that might be studied and replicated in high-risk areas.\n\n-   **Mixed clusters** demand further investigation to understand why neighboring provinces with drastically different drug abuse rates are in close proximity, potentially guiding more tailored local strategies.\n\n## **Global Measures of Spatial Autocorrelation: Geary’s C**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(combined_province_data$total_offenses, listw=weights_list)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  combined_province_data$total_offenses \nweights: weights_list   \n\nGeary C statistic standard deviate = 3.8101, p-value = 6.945e-05\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       0.87943531        1.00000000        0.00100129 \n```\n\n\n:::\n:::\n\n\n**Output Interpretation:**\n\n-   **Geary C statistic:** 0.87943531 - This value suggests a moderate positive spatial autocorrelation. It means that provinces with higher rates of total offenses tend to be located near other provinces with higher rates.\n\n-   **Standard deviate:** 3.8101 - This is the standard deviation of the Geary's C statistic under random permutations. It provides a measure of variability around the expected value of 1 under no autocorrelation.\n\n-   **p-value:** 6.945e-05 - This small p-value indicates that the observed Geary's C statistic is unlikely to occur by chance if there were no spatial autocorrelation. It provides evidence for the existence of spatial clustering in the data.\n\n-   **Alternative hypothesis:** Expectation greater than statistic - This indicates that the alternative hypothesis is that the expected value of Geary's C is greater than the observed statistic, suggesting positive spatial autocorrelation.\n\n-   **Sample estimates:**\n\n    -   **Expectation:** 1.00000000 - This is the expected value of Geary's C under random permutations.\n\n    -   **Variance:** 0.00100129 - This is the variance of Geary's C under random permutations.\n\n**Conclusion:**\n\nThe analysis suggests that there is a moderate positive spatial autocorrelation in the distribution of total offenses across the provinces in the dataset. This means that provinces with higher rates of total offenses tend to be clustered together geographically. This finding may be indicative of underlying spatial processes or factors that influence the distribution of total offenses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm_GC=geary.mc(combined_province_data$total_offenses, \n               listw=weights_list, \n               nsim=999)\nbperm_GC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  combined_province_data$total_offenses \nweights: weights_list  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.87944, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n`set.seed(1234)`: This sets the random seed to ensure reproducibility of the results.\n\n### **Output Interpretation:**\n\n#### **Geary's C Statistic:**\n\n-   **Value: 0.87943531** - The Geary's C value is less than 1, suggesting **moderate positive spatial autocorrelation**. This means that provinces with higher rates of drug offenses are located near other provinces with similarly higher rates, though the clustering is less pronounced compared to Moran's I.\n\n#### **Standard Deviate:**\n\n-   **3.8101** - This is the **Z-score** or standard deviation of the Geary’s C statistic. A Z-score greater than 2 typically indicates a significant result, and 3.8101 shows a strong deviation from what is expected under random distribution, reinforcing the presence of spatial autocorrelation.\n\n#### **p-value:**\n\n-   **6.945e-05** - The p-value is extremely small, indicating that the probability of observing this spatial clustering by chance is negligible. Therefore, there is **strong evidence** that spatial clustering exists in the data.\n\n#### **Alternative Hypothesis:**\n\n-   **Expectation greater than statistic** - This indicates that the observed value of Geary's C is lower than its expected value of 1, suggesting **positive spatial autocorrelation**.\n\n#### **Sample Estimates:**\n\n-   **Expectation: 1.00000000** - This is the expected value of Geary's C under the assumption of no spatial autocorrelation.\n\n-   **Variance: 0.00100129** - This is the variance around the expected value of Geary's C, used to determine the significance of the observed statistic.\n\n### **Conclusion:**\n\nThe results from the Geary's C statistic suggest **moderate positive spatial autocorrelation** in the distribution of drug offenses across provinces. This means that **provinces with higher drug offense rates** tend to be **geographically clustered** together, but the clustering is more localized than in the case of Moran's I. This finding highlights the existence of **regional influences**—such as **drug trafficking routes, socioeconomic conditions, or enforcement practices**—that affect neighboring provinces similarly.\n\nUnderstanding these spatial patterns can guide **targeted interventions** by focusing resources in clustered regions and exploring how neighboring areas influence each other in the context of drug offenses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm_GC$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n### **Key Observations:**\n\n#### **Distribution:**\n\n-   The histogram of simulated Geary's C values shows a roughly **bell-shaped** (normal) distribution, meaning that most of the simulated values are close to a central value, and fewer values appear at the extremes.\n\n#### **Central Tendency:**\n\n-   The distribution is centered around a value **slightly greater than 1.0**, which is the expected value of Geary’s C under the assumption of no spatial autocorrelation. This suggests that, under random spatial configurations, the majority of simulated values align with the null hypothesis (no autocorrelation).\n\n#### **Spread:**\n\n-   The relatively **narrow spread** of the distribution indicates that the simulated Geary’s C values are not highly dispersed, which is expected in the Monte Carlo permutation process. Most simulated values are clustered around the central value with limited deviation.\n\n#### **Observed Statistic:**\n\n-   The **red vertical line** on the histogram represents the **observed Geary’s C statistic**. Its position in the **right tail** of the distribution indicates that the observed statistic is relatively **high compared to the majority of simulated values**.\n\n### **Interpretation:**\n\n-   **Normality:** The approximately normal distribution of simulated Geary's C values demonstrates that the **Monte Carlo permutation test** is valid, reinforcing the **reliability of the p-value** associated with this test.\n\n-   **Central Tendency:** The fact that most simulated values are near 1.0 confirms that the **expected value of Geary's C** under random permutations is around 1.0, corresponding to **no spatial autocorrelation**.\n\n-   **Spread:** The **narrow distribution** suggests that the simulated values have a **low level of dispersion**, further supporting the statistical robustness of the test.\n\n-   **Observed Statistic:** The position of the observed Geary's C statistic in the **right tail** of the distribution indicates that it is **significantly higher than the majority of simulated values**. This strongly supports the conclusion that the observed spatial autocorrelation is **unlikely to have occurred by chance**.\n\n### **Conclusion:**\n\nThe histogram provides **clear visual evidence** of the statistical significance of the observed Geary's C statistic. The **simulated values are normally distributed** around 1.0, with the observed Geary’s C falling in the **right tail** of the distribution. This indicates that the observed spatial autocorrelation is **significant and unlikely to occur randomly**, supporting the finding of **positive spatial autocorrelation** in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(combined_province_data$total_offenses, \n                listw=weights_list, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  combined_province_data$total_offenses \nweights: weights_list  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.19036, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nSimiliarly, function `moran.mc` performs a Monte Carlo permutation test to assess the statistical significance of the observed Moran's I statistic.\n\n### **Output Interpretation:**\n\n1.  **Monte Carlo Simulation of Moran's I:**\n\n    -   This indicates that a **Monte Carlo permutation test** was conducted to evaluate the **statistical significance** of the Moran's I statistic, which measures spatial autocorrelation.\n\n2.  **Data: combined_province_data\\$total_offenses:**\n\n    -   The variable of interest in the analysis is **total_offenses**, representing the total number of drug offenses across the provinces.\n\n3.  **Weights: weights_list:**\n\n    -   The spatial weights matrix used for the analysis is designated as **weights_list**, which defines the spatial relationships between the provinces.\n\n4.  **Number of Simulations + 1: 1000:**\n\n    -   A total of **1000 simulations** were performed, including one for the observed data. This number indicates the robustness of the statistical assessment, as a higher number of simulations generally increases reliability.\n\n5.  **Statistic = 0.19036:**\n\n    -   The **observed Moran's I statistic** is **0.19036**. This value suggests a **weak positive spatial autocorrelation**, indicating that provinces with higher drug offense rates tend to be clustered together.\n\n6.  **Observed Rank 1000:**\n\n    -   This indicates that the **observed Moran's I statistic** is the **largest** among all 1000 simulated values, suggesting a strong deviation from randomness in the observed data.\n\n7.  **p-value = 0.001:**\n\n    -   The **p-value** of **0.001** indicates that the observed Moran's I statistic is **highly unlikely to occur by chance** if there were no spatial autocorrelation. This small p-value provides **strong evidence** for the existence of spatial clustering in the drug offense data.\n\n8.  **Alternative Hypothesis: Greater:**\n\n    -   The alternative hypothesis states that the expected value of Moran's I is greater than the observed statistic. This implies that the analysis is specifically testing for **positive spatial autocorrelation** in the data.\n\n### **Conclusion:**\n\nThe output indicates that the **Monte Carlo permutation test** has provided robust statistical evidence supporting the existence of **positive spatial autocorrelation** in the distribution of drug offenses across provinces. The **observed Moran's I statistic** of **0.19036**, combined with the **p-value of 0.001**, strongly suggests that provinces with higher drug offenses tend to cluster together, rather than being distributed randomly. This finding can inform further investigations into the factors contributing to this spatial pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.002503914\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n### **Key Observations:**\n\n1.  **Distribution:**\n\n    -   The histogram displays a **right-skewed distribution**, indicating a longer tail on the right side. This suggests that the simulated Moran's I values are more frequently higher than the mean.\n\n2.  **Central Tendency:**\n\n    -   The distribution appears to be centered around a value slightly greater than **0**, implying that most simulated values cluster close to **0**. This is consistent with the expectation of no spatial autocorrelation.\n\n3.  **Spread:**\n\n    -   The distribution is **relatively wide**, suggesting that the simulated Moran's I values are dispersed over a broader range. This indicates variability in the spatial autocorrelation across the simulations.\n\n4.  **Observed Statistic:**\n\n    -   The **red vertical line**, representing the observed Moran's I statistic, is located towards the **right tail** of the distribution. This indicates that the observed value is relatively high compared to the majority of the simulated values.\n\n### **Interpretation:**\n\n1.  **Skewness:**\n\n    -   The **right-skewed distribution** suggests that there are some simulated values significantly higher than the others. This could be attributed to the presence of **strong spatial clusters** or other influential factors affecting the distribution of Moran's I.\n\n2.  **Central Tendency:**\n\n    -   The clustering of most simulated values around **0** indicates that under random permutations, the Moran's I statistic tends to be near **0**, which aligns with the null hypothesis of no spatial autocorrelation.\n\n3.  **Spread:**\n\n    -   The **relatively wide distribution** suggests that while the values cluster around the center, they also exhibit variability. This is expected in a Monte Carlo permutation test, where randomness can produce a range of outcomes.\n\n4.  **Observed Statistic:**\n\n    -   The position of the observed Moran's I statistic in the **right tail** signifies that it is notably different from the simulated values, reinforcing the notion that the observed spatial autocorrelation is unlikely to result from random chance.\n\n### **Conclusion:**\n\nThe histogram visually substantiates the statistical significance of the observed Moran's I statistic. The **right-skewed distribution** of simulated values indicates that the observed Moran's I is comparatively high relative to the majority of simulated outcomes. This supports the conclusion of **positive spatial autocorrelation** in the dataset, suggesting that areas with higher drug offenses are clustered together rather than randomly distributed. This insight can guide further exploration into the underlying factors influencing these spatial patterns.\n\n#### Mapping the local Moran’s I\n\nBefore mapping the local Moran’s I map, it is wise to append the local Moran’s I dataframe (i.e. localMI) onto hunan SpatialPolygonDataFrame. The code chunks below can be used to perform the task. The out SpatialPolygonDataFrame is called *province.localMI*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince.localMI <- cbind(combined_province_data,local_moran) %>%\n  rename(Pr.Ii = Pr.z....E.Ii..)\n```\n:::\n\n\nUsing choropleth mapping functions of **tmap** package, we can plot the local Moran’s I values by using the code chunks below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(province.localMI) +\n  tm_fill(col = \"Ii\", \n          style = \"pretty\",\n          palette = \"RdBu\",\n          title = \"local moran statistics\") +\n  tm_borders(alpha = 0.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nVariable(s) \"Ii\" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n### **Key Observations:**\n\n1.  **Spatial Clustering:**\n\n    -   The map effectively illustrates **distinct clusters** of provinces based on the Local Moran's I statistic, suggesting significant **spatial autocorrelation** in the distribution of the variable, likely related to drug offenses.\n\n2.  **Hotspots and Coldspots:**\n\n    -   **Hotspots:** Provinces in the **northern** and **southern regions** are marked with darker shades, indicating that these areas have high values of the variable and are surrounded by other regions with similarly high values.\n\n    -   **Coldspots:** In contrast, certain provinces in the **central** and **southern regions** exhibit lighter shades, suggesting they have low values and are also surrounded by other low-value areas.\n\n3.  **Mixed Clusters:**\n\n    -   The presence of **mixed clusters** (e.g., low-high or high-low) indicates **complex spatial relationships**, highlighting areas where drug offenses may not follow simple patterns of high or low values.\n\n### **Potential Explanations and Further Analysis:**\n\nGiven the context of drug offenses in Thailand, several factors may contribute to these observed patterns:\n\n1.  **Geographical Factors:**\n\n    -   The **proximity to borders** with countries like Myanmar and Laos may significantly influence drug trafficking routes. This geographical positioning can lead to concentrated areas of drug activity, forming the identified hotspots.\n\n2.  **Socioeconomic Conditions:**\n\n    -   Areas with **higher poverty rates**, **unemployment**, and a **lack of educational opportunities** may correlate with increased rates of drug offenses. These socioeconomic challenges can foster environments conducive to drug-related activities.\n\n3.  **Governance and Law Enforcement:**\n\n    -   Variations in the **effectiveness of law enforcement** and anti-drug initiatives across regions can impact how drug offenses are distributed spatially. Regions with stronger law enforcement may show lower rates of drug offenses, contributing to the coldspots.\n\n4.  **Drug Production and Trafficking:**\n\n    -   Understanding the specific **types of drugs** involved in the offenses and their **production and trafficking routes** can provide deeper insights into the observed spatial patterns. Certain drugs may be more prevalent in specific areas, influenced by local production capabilities and trafficking networks.\n\n### **Conclusion:**\n\nThe map serves as a valuable visual tool for understanding the **spatial distribution** of drug offenses in Thailand and the **statistical significance** of the identified clusters. By closely examining the hotspots and coldspots, researchers and policymakers can better understand the underlying factors that drive these patterns. This knowledge can inform **targeted interventions** to effectively address the drug problem, tailoring strategies to the specific needs and conditions of different regions.\n\n# Computing local Gi\\* statistics\n\nneed to derive a spatial weight matrix before we can compute local Gi\\* statistics. Code chunk below will be used to derive a spatial weight matrix by using sfdep functions and tidyverse approach\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|eval: false\nwm_thai <- combined_province_data %>% \n  mutate(nb=st_contiguity(geometry),\n         wts = st_inverse_distance(nb,geometry,\n                                   scale=1,\n                                   alpha=1),\n         .before = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n! Polygon provided. Using point on surface.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `stopifnot()`.\nℹ In argument: `wts = st_inverse_distance(nb, geometry, scale = 1, alpha = 1)`.\nCaused by warning in `st_point_on_surface.sfc()`:\n! st_point_on_surface may not give correct results for longitude/latitude data\n```\n\n\n:::\n:::\n\n\n### Save Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(wm_thai,\"data/rds/wm_thai.rds\")\n```\n:::\n\n\n### Read Derived data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_thai<- read_rds(\"data/rds/wm_thai.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA <- wm_thai %>% \n  mutate(local_Gi = local_gstar_perm(\n    total_offenses,nb,wt,nsim=99),\n    .before=1) %>% \n      unnest(local_Gi)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_sig <- HCSA %>% \n  filter(p_sim<0.05)\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ntmap mode set to plotting\n```\n\n\n:::\n\n```{.r .cell-code}\ntm_shape(HCSA)+\n  tm_polygons()+\n  tm_borders(alpha=0.5)+\ntm_shape(HCSA_sig)+\n  tm_fill(\"gi_star\")+\n  tm_borders(alpha=0.4)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: One tm layer group has duplicated layer types, which are omitted. To\ndraw multiple layers of the same type, use multiple layer groups (i.e. specify\ntm_shape prior to each of them).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nVariable(s) \"gi_star\" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](take_home_ex2_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n### **Key Observations:**\n\n1.  **Spatial Clustering:**\n\n    -   The map effectively illustrates **significant spatial clustering** of drug abuse cases across Thailand. Distinct **hotspots** and **coldspots** are clearly visible, indicating areas with concentrated levels of drug abuse.\n\n2.  **Hotspots:**\n\n    -   Provinces located in the **northern** and **southern regions** display higher **Geary's I values**, signifying **stronger spatial autocorrelation**. This suggests that these areas likely have higher levels of drug abuse clustered together, which could be indicative of localized issues.\n\n3.  **Coldspots:**\n\n    -   In contrast, some provinces in the **central region** exhibit **lower Geary's I values**. This may imply **weaker spatial autocorrelation** and potentially lower levels of drug abuse, or more dispersed patterns of drug use.\n\n### **Potential Explanations and Further Analysis:**\n\n1.  **Geographical Factors:**\n\n    -   The **proximity to borders** with neighboring countries, such as **Myanmar** and **Laos**, may significantly influence drug trafficking routes. This geographic positioning could facilitate drug flow and contribute to the observed clustering of drug abuse cases in those regions.\n\n2.  **Socioeconomic Conditions:**\n\n    -   **Poverty**, **unemployment**, and a **lack of educational opportunities** are factors that may correlate with increased drug abuse rates. Regions facing these socioeconomic challenges could see higher levels of clustering as individuals may turn to substance abuse in the absence of viable opportunities.\n\n3.  **Governance and Law Enforcement:**\n\n    -   Variations in the **effectiveness of law enforcement** agencies and anti-drug initiatives across different provinces could impact the **spatial distribution** of drug abuse. Regions with stronger enforcement might exhibit lower rates of drug abuse due to proactive measures, while areas with lax enforcement could show increased clustering.\n\n4.  **Drug Production and Trafficking:**\n\n    -   Gaining insights into the specific **types of drugs** involved and their respective **production and trafficking routes** could illuminate the spatial patterns of drug abuse. Understanding these dynamics may reveal underlying factors contributing to the clustering seen in the hotspots.\n\n### **Conclusion:**\n\nThe map serves as an invaluable tool for visualizing the **spatial distribution** of drug abuse in Thailand, highlighting the **statistical significance** of the identified clusters. By analyzing the **hotspots** and **coldspots**, researchers and policymakers can better understand the complex interplay of factors driving these patterns. This understanding can lead to the development of **targeted interventions** that address the specific needs of affected regions, ultimately aiding in the fight against drug abuse in Thailand.\n\n# Conclusion and Reflection\n\nThe spatial analysis of drug abuse indicators across Thailand reveals significant regional variations in drug offenses, highlighting the impact of Thailand's geographical proximity to the Golden Triangle, a notorious drug production area. Provinces near this region exhibit higher rates of drug-related offenses, underscoring their role as both consumption areas and transit hubs for drug trafficking. The use of spatial autocorrelation methods, such as global and local Moran's I, confirmed clusters of high drug offenses in these provinces. This suggests that drug-related activities are not randomly distributed but are spatially concentrated in specific areas.\n\nThe findings further emphasize the vulnerability of certain provinces, particularly those with strong transportation links and infrastructure developments, which facilitate the movement of drugs. The high concentration of drug offenses among youth, especially vocational school students, calls for targeted intervention programs aimed at this demographic.\n\n### Reflection\n\nThis assignment underscored the importance of using spatial analysis tools to understand the geographic distribution of social issues like drug abuse. By applying techniques such as spatial autocorrelation, we gained insights into the areas most affected by drug trafficking and consumption in Thailand. The data-driven approach helps inform policy decisions and resource allocation, allowing authorities to focus on high-risk regions and populations.\n\nThe exercise also illustrated the complexity of addressing drug abuse in Thailand, as it is influenced by a combination of geopolitical factors, infrastructural developments, and socio-economic conditions. Future studies could explore the relationship between drug offenses and other socio-economic variables, such as income levels, education, and employment, to further refine prevention strategies. Overall, spatial analysis provided a valuable lens through which to examine drug-related issues and supports the development of more effective, geo graphically targeted interventionss\n",
    "supporting": [
      "take_home_ex2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}